# Generated by Django 2.1.2 on 2018-12-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bamazon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=200)),
                ('over_head_costs', models.IntegerField()),
                ('product_sales', models.IntegerField()),
            ],
        ),
    ]
